ALTER TABLE clients ADD COLUMN IF NOT EXISTS dlr_webhook_url TEXT DEFAULT NULL;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS dlr_webhook_secret TEXT DEFAULT NULL;

ALTER TABLE carriers ADD COLUMN IF NOT EXISTS dlr_callback_url_template TEXT DEFAULT NULL;
ALTER TABLE carriers ADD COLUMN IF NOT EXISTS dlr_field_name TEXT DEFAULT NULL;
ALTER TABLE carriers ADD COLUMN IF NOT EXISTS dlr_inbound_secret TEXT DEFAULT NULL;
ALTER TABLE carriers ADD COLUMN IF NOT EXISTS dlr_message_id_field TEXT DEFAULT NULL;
ALTER TABLE carriers ADD COLUMN IF NOT EXISTS dlr_status_field TEXT DEFAULT NULL;
ALTER TABLE carriers ADD COLUMN IF NOT EXISTS dlr_status_map JSONB DEFAULT NULL;
ALTER TABLE carriers ADD COLUMN IF NOT EXISTS smpp_source_addr_ton TEXT NOT NULL DEFAULT 'dynamic';
ALTER TABLE carriers ADD COLUMN IF NOT EXISTS smpp_source_addr_npi TEXT NOT NULL DEFAULT 'dynamic';
ALTER TABLE carriers ADD COLUMN IF NOT EXISTS smpp_dest_addr_ton TEXT NOT NULL DEFAULT 'dynamic';
ALTER TABLE carriers ADD COLUMN IF NOT EXISTS smpp_dest_addr_npi TEXT NOT NULL DEFAULT 'dynamic';

ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS dlr_requested BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS dlr_webhook_url TEXT DEFAULT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS dlr_status TEXT DEFAULT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS dlr_received_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS dlr_forwarded_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS dlr_forward_status TEXT DEFAULT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS dlr_forward_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS source_addr_ton SMALLINT DEFAULT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS source_addr_npi SMALLINT DEFAULT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS dest_addr_ton SMALLINT DEFAULT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS dest_addr_npi SMALLINT DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_sms_logs_dlr_requested
    ON sms_logs (dlr_requested) WHERE dlr_requested = TRUE;
CREATE INDEX IF NOT EXISTS idx_sms_logs_dlr_status
    ON sms_logs (dlr_status) WHERE dlr_status IS NOT NULL;
